Name:           ros-jade-interval-intersection
Version:        0.10.14
Release:        0%{?dist}
Summary:        ROS interval_intersection package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/interval_intersection
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-jade-actionlib
Requires:       ros-jade-actionlib-msgs
Requires:       ros-jade-calibration-msgs
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-rosconsole
Requires:       ros-jade-roscpp
Requires:       ros-jade-roscpp-serialization
Requires:       ros-jade-rostime
Requires:       ros-jade-std-msgs
BuildRequires:  boost-devel
BuildRequires:  ros-jade-actionlib
BuildRequires:  ros-jade-actionlib-msgs
BuildRequires:  ros-jade-calibration-msgs
BuildRequires:  ros-jade-catkin >= 0.5.68
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-rosconsole
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-roscpp-serialization
BuildRequires:  ros-jade-rostime
BuildRequires:  ros-jade-std-msgs

%description
Tools for calculating the intersection of interval messages coming in on several
topics. This package is experimental and unstable. Expect its APIs to change.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Sun Apr 17 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.10.14-0
- Autogenerated by Bloom

* Sun Jan 18 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.10.13-0
- Autogenerated by Bloom

